<?php

namespace PisteGouvFr\Api\ChorusPro\Parameter\ReferentielDesOrganisations;

/**
 * @method filtrerParLibelleOrganisation( RechercheFieldString $fieldRule )
 * @method filtrerParNumeroTvaIntracommunautaire( RechercheFieldString $fieldRule )
 * @method filtrerParTypeOrganisation( RechercheFieldString $fieldRule )
 * @method filtrerParContactPrincipal( RechercheFieldString $fieldRule )
 * @method filtrerParOrganisationParent( RechercheFieldString $fieldRule )
 * @method filtrerParEstCentreGestionAgricole( RechercheFieldBoolean $fieldRule )
 * @method filtrerParGestionNumeroEJOuCodeService( RechercheFieldBoolean $fieldRule )
 * @method filtrerParNumeroPacage( RechercheFieldBoolean $fieldRule )
 * @method filtrerParStatus( RechercheFieldBoolean $fieldRule )
 * @method filtrerParIdentifiant( RechercheFieldString $fieldRule )
 * @method filtrerParTypeIdentifiant( RechercheFieldString $fieldRule )
 * @method filtrerParCategorieFournisseurMemoireId( RechercheFieldInt $fieldRule )
 * @method filtrerParCategorieBeneficiaireId( RechercheFieldInt $fieldRule )
 * @method filtrerParAdresse( RechercheFieldString $fieldRule )
 * @method filtrerParComplementAdresse1( RechercheFieldString $fieldRule )
 * @method filtrerParComplementAdresse2( RechercheFieldString $fieldRule )
 * @method filtrerParCodePostal( RechercheFieldString $fieldRule )
 * @method filtrerParVille( RechercheFieldString $fieldRule )
 * @method filtrerParPays( RechercheFieldString $fieldRule )
 * @method filtrerParAdresseElectronique( RechercheFieldString $fieldRule )
 * @method filtrerParTelephone( RechercheFieldString $fieldRule )
 * @method filtrerParRecevoirCyclesViesEdi( RechercheFieldBoolean $fieldRule )
 * @method filtrerParEmetteurFluxEdi( RechercheFieldBoolean $fieldRule )
 * @method filtrerParNonDiffusibleInsee( RechercheFieldBoolean $fieldRule )
 * @method filtrerParDerniereMaj( RechercheFieldDateTime $fieldRule )
 * @method filtrerParUuid( RechercheFieldString $fieldRule )
 * @method filtrerParNomStructure( RechercheFieldString $fieldRule )
 * @method filtrerParPrenomStructure( RechercheFieldString $fieldRule )
 * @method filtrerParNumeroRcsStructure( RechercheFieldString $fieldRule )
 * @method filtrerParNumeroEjDoitEtreRenseigne( RechercheFieldBoolean $fieldRule )
 * @method filtrerParCodeServiceDoitEtreRenseigne( RechercheFieldBoolean $fieldRule )
 * @method filtrerParStatutMiseEnPaiementNestPasRemonte( RechercheFieldBoolean $fieldRule )
 * @method filtrerParAvecMOA( RechercheFieldBoolean $fieldRule )
 * @method filtrerParEstMOAUniquement( RechercheFieldBoolean $fieldRule )
 * @method filtrerParStructureOrigine( RechercheFieldInt $fieldRule )
 */
class StructureRechercheRequete extends RechercheRequete {

    protected static function rechercheFieldsDefinition(): RechercheFieldsDefinition {
        return ( new RechercheFieldsDefinition() )
            ->addDef( 'libelleOrganisation', RechercheFieldString::class )
            ->addDef( 'numeroTvaIntracommunautaire', RechercheFieldString::class )
            ->addDef( 'typeOrganisation', RechercheFieldString::class )
            ->addDef( 'contactPrincipal', RechercheFieldString::class )
            ->addDef( 'organisationParent', RechercheFieldString::class )
            ->addDef( 'estCentreGestionAgricole', RechercheFieldBoolean::class )
            ->addDef( 'gestionNumeroEJOuCodeService', RechercheFieldBoolean::class )
            ->addDef( 'numeroPacage', RechercheFieldBoolean::class )
            ->addDef( 'status', RechercheFieldBoolean::class )
            ->addDef( 'identifiant', RechercheFieldString::class )
            ->addDef( 'typeIdentifiant', RechercheFieldString::class )
            ->addDef( 'categorieFournisseurMemoireId', RechercheFieldInt::class )
            ->addDef( 'categorieBeneficiaireId', RechercheFieldInt::class )
            ->addDef( 'adresse', RechercheFieldString::class )
            ->addDef( 'complementAdresse1', RechercheFieldString::class )
            ->addDef( 'complementAdresse2', RechercheFieldString::class )
            ->addDef( 'codePostal', RechercheFieldString::class )
            ->addDef( 'ville', RechercheFieldString::class )
            ->addDef( 'pays', RechercheFieldString::class )
            ->addDef( 'adresseElectronique', RechercheFieldString::class )
            ->addDef( 'telephone', RechercheFieldString::class )
            ->addDef( 'recevoirCyclesViesEdi', RechercheFieldBoolean::class )
            ->addDef( 'emetteurFluxEdi', RechercheFieldBoolean::class )
            ->addDef( 'nonDiffusibleInsee', RechercheFieldBoolean::class )
            ->addDef( 'derniereMaj', RechercheFieldDateTime::class )
            ->addDef( 'uuid', RechercheFieldString::class )
            ->addDef( 'nomStructure', RechercheFieldString::class )
            ->addDef( 'prenomStructure', RechercheFieldString::class )
            ->addDef( 'numeroRcsStructure', RechercheFieldString::class )
            ->addDef( 'numeroEjDoitEtreRenseigne', RechercheFieldBoolean::class )
            ->addDef( 'codeServiceDoitEtreRenseigne', RechercheFieldBoolean::class )
            ->addDef( 'statutMiseEnPaiementNestPasRemonte', RechercheFieldBoolean::class )
            ->addDef( 'avecMOA', RechercheFieldBoolean::class )
            ->addDef( 'estMOAUniquement', RechercheFieldBoolean::class )
            ->addDef( 'structureOrigine', RechercheFieldInt::class )
            ->addDef( 'raisonSociale', RechercheFieldString::class )
            ->addDef( 'categorieJuridique', RechercheFieldString::class )
            ->addDef( 'categorieEntreprise', RechercheFieldString::class );
    }

}