<?php

namespace PisteGouvFr\Api\ChorusPro\Parameter\ReferentielDesOrganisations;

/**
 * @method StructureRechercheRequete filtrerParLibelleOrganisation( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParNumeroTvaIntracommunautaire( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParTypeOrganisation( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParContactPrincipal( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParOrganisationParent( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParEstCentreGestionAgricole( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParGestionNumeroEJOuCodeService( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParNumeroPacage( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParStatus( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParIdentifiant( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParTypeIdentifiant( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParCategorieFournisseurMemoireId( RechercheFieldInt $fieldRule )
 * @method StructureRechercheRequete filtrerParCategorieBeneficiaireId( RechercheFieldInt $fieldRule )
 * @method StructureRechercheRequete filtrerParAdresse( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParComplementAdresse1( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParComplementAdresse2( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParCodePostal( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParVille( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParPays( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParAdresseElectronique( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParTelephone( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParRecevoirCyclesViesEdi( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParEmetteurFluxEdi( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParNonDiffusibleInsee( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParDerniereMaj( RechercheFieldDateTime $fieldRule )
 * @method StructureRechercheRequete filtrerParUuid( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParNomStructure( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParPrenomStructure( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParNumeroRcsStructure( RechercheFieldString $fieldRule )
 * @method StructureRechercheRequete filtrerParNumeroEjDoitEtreRenseigne( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParCodeServiceDoitEtreRenseigne( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParStatutMiseEnPaiementNestPasRemonte( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParAvecMOA( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParEstMOAUniquement( RechercheFieldBoolean $fieldRule )
 * @method StructureRechercheRequete filtrerParStructureOrigine( RechercheFieldInt $fieldRule )
 */
class StructureRechercheRequete extends RechercheRequete {

    protected static function rechercheFieldsDefinition(): RechercheFieldsDefinition {
        return ( new RechercheFieldsDefinition() )
            ->addDef( 'libelleOrganisation', RechercheFieldString::class )
            ->addDef( 'numeroTvaIntracommunautaire', RechercheFieldString::class )
            ->addDef( 'typeOrganisation', RechercheFieldString::class )
            ->addDef( 'contactPrincipal', RechercheFieldString::class )
            ->addDef( 'organisationParent', RechercheFieldString::class )
            ->addDef( 'estCentreGestionAgricole', RechercheFieldBoolean::class )
            ->addDef( 'gestionNumeroEJOuCodeService', RechercheFieldBoolean::class )
            ->addDef( 'numeroPacage', RechercheFieldBoolean::class )
            ->addDef( 'status', RechercheFieldBoolean::class )
            ->addDef( 'identifiant', RechercheFieldString::class )
            ->addDef( 'typeIdentifiant', RechercheFieldString::class )
            ->addDef( 'categorieFournisseurMemoireId', RechercheFieldInt::class )
            ->addDef( 'categorieBeneficiaireId', RechercheFieldInt::class )
            ->addDef( 'adresse', RechercheFieldString::class )
            ->addDef( 'complementAdresse1', RechercheFieldString::class )
            ->addDef( 'complementAdresse2', RechercheFieldString::class )
            ->addDef( 'codePostal', RechercheFieldString::class )
            ->addDef( 'ville', RechercheFieldString::class )
            ->addDef( 'pays', RechercheFieldString::class )
            ->addDef( 'adresseElectronique', RechercheFieldString::class )
            ->addDef( 'telephone', RechercheFieldString::class )
            ->addDef( 'recevoirCyclesViesEdi', RechercheFieldBoolean::class )
            ->addDef( 'emetteurFluxEdi', RechercheFieldBoolean::class )
            ->addDef( 'nonDiffusibleInsee', RechercheFieldBoolean::class )
            ->addDef( 'derniereMaj', RechercheFieldDateTime::class )
            ->addDef( 'uuid', RechercheFieldString::class )
            ->addDef( 'nomStructure', RechercheFieldString::class )
            ->addDef( 'prenomStructure', RechercheFieldString::class )
            ->addDef( 'numeroRcsStructure', RechercheFieldString::class )
            ->addDef( 'numeroEjDoitEtreRenseigne', RechercheFieldBoolean::class )
            ->addDef( 'codeServiceDoitEtreRenseigne', RechercheFieldBoolean::class )
            ->addDef( 'statutMiseEnPaiementNestPasRemonte', RechercheFieldBoolean::class )
            ->addDef( 'avecMOA', RechercheFieldBoolean::class )
            ->addDef( 'estMOAUniquement', RechercheFieldBoolean::class )
            ->addDef( 'structureOrigine', RechercheFieldInt::class )
            ->addDef( 'raisonSociale', RechercheFieldString::class )
            ->addDef( 'categorieJuridique', RechercheFieldString::class )
            ->addDef( 'categorieEntreprise', RechercheFieldString::class );
    }

}