<?php

namespace PisteGouvFr\Api\ChorusPro\Type;


interface ITypeFactureTravaux {


    const DP_DE_SOUSTRAITANT_TRAVAUX                  = 'DP_DE_SOUSTRAITANT_TRAVAUX';
    const PROJET_DECOMPTE_MENSUEL                     = 'PROJET_DECOMPTE_MENSUEL';
    const ETAT_ACOMPTE                                = 'ETAT_ACOMPTE';
    const ETAT_ACOMPTE_VALIDE                         = 'ETAT_ACOMPTE_VALIDE';
    const PROJET_DECOMPTE_FINAL                       = 'PROJET_DECOMPTE_FINAL';
    const PROJET_DECOMPTE_GENERAL                     = 'PROJET_DECOMPTE_GENERAL';
    const PROJET_DECOMPTE_GENERAL_PROCEDURE_TACITE    = 'PROJET_DECOMPTE_GENERAL_PROCEDURE_TACITE';
    const DECOMPTE_GENERAL                            = 'DECOMPTE_GENERAL';
    const DECOMPTE_GENERAL_SIGNE                      = 'DECOMPTE_GENERAL_SIGNE';
    const DECOMPTE_GENERAL_DEFINITIF_TACITE           = 'DECOMPTE_GENERAL_DEFINITIF_TACITE';
    const DECOMPTE_GENERAL_DEFINITIF_PROCEDURE_TACITE = 'DECOMPTE_GENERAL_DEFINITIF_PROCEDURE_TACITE';

}
